spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:defaultItem.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true # group, order 등 키워드 entity 명으로 사용하기 위해 추가
  h2:
    console:
      enabled: true
---

